server.port=8080

# PostgresSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/payment-db
spring.datasource.username=admin
spring.datasource.password=secret
spring.datasource.driver-class-name=org.postgresql.Driver

# SQL Initialization
spring.sql.init.mode=always
spring.sql.init.platform=postgresql

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false

# Jackson
spring.jackson.serialization.indent-output=true
spring.jackson.default-property-inclusion=non_null
